name: 'Review Reminder'
description: 'Notify in chat about build results.'
author: 'Logan Ramos'
inputs:
  token:
    description: GitHub token.
    default: ${{ github.token }}
    required: true
  slack_token:
    description: Slack token.
    required: true
  tenantId:
    description: "The service tenant id of the service which serves the VS Code Tools API"
    required: true
  clientId:
    description: "The service client id of the service which serves the VS Code Tools API"
    required: true
  clientSecret:
    description: "The service client secret of the service which serves the VS Code Tools API"
    required: true
  clientScope:
    description: "The service client scope of the service which serves the VS Code Tools API"
    required: true
runs:
  using: 'node16'
  main: 'index.js'
